#!/bin/bash

infoHelp="Importer - wrzuca kolekcję do lokalnego hosta z pliku json. Użycie:\n
		\bKolejność argumentów może być jest istotna.\n
		*0 argumentów - skrypt odpyta o wszystkie potrzebne informacje do prawidłowego importu danych do kolekcji\n\n
		*2 argumenty - importowanie do kolekcji o takiej samej nazwie jak nazwa pliku (np: importer nazwa_bazy nazwa_pliku)\n\n
		*3 argumenty - importowanie do kolekcji z konkretnego pliku json (np: importer nazwa_bazy nazwa_kolekcji nazwa_pliku.json)\n"
		
if [ "$#" -eq 0 ]
	then
	echo "Nie podałeś żadnego argumentu!"
	echo "Podaj nazwę bazy do jakiej zaimportować:"
	read db_name
	echo "Podaj kolekcję do jakiej chcesz wrzucić dane:"
	read collection
	echo "Podaj nazwę pliku json (bez rozszerzenia .json)"
	read fileName
	mongoimport --db $db_name --collection $collection --type json --file $fileName.json --jsonArray
elif [ "$#" -eq 1 -a "$1" = "help" ]
	then
	echo -e $infoHelp
elif [ "$#" -eq 2 ]
	then
	mongoimport --db $1 --collection $2 --type json --file $2.json --jsonArray
elif [ "$#" -eq 3 ]
	then
	mongoimport --db $1 --collection $2 --type json --file $3 --jsonArray
else
	echo -e $infoHelp
fi
